import { db } from '@/config/firebase';
import {
  collection,
  doc,
  writeBatch,
  getDocs,
  Timestamp,
} from 'firebase/firestore';
import type { MenuCategory, MenuItem } from '@/types';

export const BURGONOMICS_DEFAULT_CATEGORIES: MenuCategory[] = [
  { id: 'cat_burgers', name: 'Gourmet Veg Burgers', sortOrder: 1, active: true },
  { id: 'cat_combos', name: 'Meal Combos & Boxes', sortOrder: 2, active: true },
  { id: 'cat_sides', name: 'Crispy Sides & Fries', sortOrder: 3, active: true },
  { id: 'cat_beverages', name: 'Shakes & Beverages', sortOrder: 4, active: true },
];

export const BURGONOMICS_63_ITEMS: Omit<MenuItem, 'lastSyncedAt'>[] = [
  // --- Category 1: Gourmet Veg Burgers (20 Items) ---
  {
    id: 'itm_classic_crunch',
    petpoojaItemId: 'PP-BRG-101',
    name: 'Classic Veggie Crunch Burger',
    description: 'Crispy spiced vegetable patty, fresh butterhead lettuce, sliced ripe tomatoes, house burger relish.',
    price: 129,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_aloo_tikki_supreme',
    petpoojaItemId: 'PP-BRG-102',
    name: 'Aloo Tikki Supreme Burger',
    description: 'Golden spiced potato & pea patty, crunchy onions, tangy imli sauce and mint mayo.',
    price: 99,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_paneer_makhani_burst',
    petpoojaItemId: 'PP-BRG-103',
    name: 'Paneer Makhani Burst Burger',
    description: 'Grilled cottage cheese steak dipped in rich butter makhani gravy with butter toasted brioche bun.',
    price: 199,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_cheese_lava_monster',
    petpoojaItemId: 'PP-BRG-104',
    name: 'Cheese Lava Monster Burger',
    description: 'Molten cheddar cheese core patty that oozes on the first bite, served with smoked paprika sauce.',
    price: 249,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1521305916504-4a1121188589?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_smoky_bbq_mushroom',
    petpoojaItemId: 'PP-BRG-105',
    name: 'Smoky BBQ Portobello Burger',
    description: 'Chargrilled portobello mushrooms, caramelized onions, smoked chipotle BBQ glaze, Swiss cheese.',
    price: 219,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_mexican_fiery_jalapeno',
    petpoojaItemId: 'PP-BRG-106',
    name: 'Mexican Fiery Jalapeño Burger',
    description: 'Black bean & roasted corn patty, pickled jalapeños, spicy habanero salsa, crispy tortilla crisps.',
    price: 189,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_peri_peri_crispy_veg',
    petpoojaItemId: 'PP-BRG-107',
    name: 'Peri Peri Crispy Veg Burger',
    description: 'Spicy peri peri marinated patty, crunchy iceberg lettuce, chili garlic mayo in sesame bun.',
    price: 149,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1549611016-3a70d82b5040?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_truffle_butter_delight',
    petpoojaItemId: 'PP-BRG-108',
    name: 'Truffle Butter Wild Mushroom Burger',
    description: 'Wild forest mushroom ragout, white truffle aioli, melted provolone, arugula leaves.',
    price: 279,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_schezwan_paneer_crunch',
    petpoojaItemId: 'PP-BRG-109',
    name: 'Schezwan Paneer Crunch Burger',
    description: 'Crispy panko-coated paneer patty, fiery Szechuan wok reduction, Asian spring slaw.',
    price: 179,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_double_decker_cheese',
    petpoojaItemId: 'PP-BRG-110',
    name: 'Double Decker Beast Burger',
    description: 'Twin herb patties, double American cheddar slices, pickle relish, thousand island sauce.',
    price: 239,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1583032015879-1c9ec8d011f0?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_guacamole_crunch',
    petpoojaItemId: 'PP-BRG-111',
    name: 'Fresh Guacamole Smash Burger',
    description: 'Hand-mashed Hass avocado guacamole, crispy lentil & veggie patty, sun-dried tomatoes.',
    price: 229,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_tandoori_soya_chaap',
    petpoojaItemId: 'PP-BRG-112',
    name: 'Tandoori Soya Chaap Burger',
    description: 'Smoky clay-oven spiced soya chaap, pickled onions, spicy mint chutney, toasted buns.',
    price: 169,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_jalapeno_cream_cheese',
    petpoojaItemId: 'PP-BRG-113',
    name: 'Jalapeño Cream Cheese Melt',
    description: 'Herb patty filled with whipped cream cheese, fire roasted jalapeños, cheddar melt.',
    price: 199,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1547584370-2cc98b8b8dc8?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_moroccan_falafel_burger',
    petpoojaItemId: 'PP-BRG-114',
    name: 'Moroccan Spiced Falafel Burger',
    description: 'Crispy chickpea & herb falafel patty, garlic tahini sauce, pickled cucumber ribbons.',
    price: 159,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_cheesy_corn_spinach',
    petpoojaItemId: 'PP-BRG-115',
    name: 'Cheesy Sweet Corn & Spinach Burger',
    description: 'Creamy American sweet corn and baby spinach patty, mozzarella crust, ranch dressing.',
    price: 169,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_smoky_chipotle_paneer',
    petpoojaItemId: 'PP-BRG-116',
    name: 'Smoky Chipotle Crispy Paneer',
    description: 'Panko paneer patty coated with smoky chipotle rub, sliced gherkins, yellow cheddar.',
    price: 209,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_korean_gochujang_veg',
    petpoojaItemId: 'PP-BRG-117',
    name: 'Korean Sticky Gochujang Burger',
    description: 'Glazed Gochujang crispy patty, toasted sesame slaw, pickled radish, spicy mayo.',
    price: 189,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_caramelized_onion_swiss',
    petpoojaItemId: 'PP-BRG-118',
    name: 'Caramelized Onion & Swiss Burger',
    description: 'Slow cooked sweet caramelized onions, roasted garlic butter, melted Swiss cheese, herb patty.',
    price: 219,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_hot_honey_crispy_paneer',
    petpoojaItemId: 'PP-BRG-119',
    name: 'Hot Honey Drizzle Paneer Burger',
    description: 'Crispy fried paneer dipped in vegan hot chili honey drizzle, butter pickles, purple cabbage.',
    price: 219,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1521305916504-4a1121188589?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_mini_slider_trio',
    petpoojaItemId: 'PP-BRG-120',
    name: 'Mini Gourmet Slider Trio',
    description: 'Sampler box of 3 mini burgers: 1 Classic Crunch, 1 Paneer Makhani, 1 Cheese Lava.',
    price: 269,
    categoryId: 'cat_burgers',
    image: 'https://images.unsplash.com/photo-1549611016-3a70d82b5040?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },

  // --- Category 2: Meal Combos & Boxes (13 Items) ---
  {
    id: 'itm_combo_classic_meal',
    petpoojaItemId: 'PP-CMB-201',
    name: 'Classic Veggie Meal for 1',
    description: 'Classic Veggie Crunch Burger + Salted French Fries + Coke Can (300ml).',
    price: 219,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_combo_paneer_burst_meal',
    petpoojaItemId: 'PP-CMB-202',
    name: 'Paneer Makhani Feast Meal',
    description: 'Paneer Makhani Burst Burger + Peri Peri Fries + Belgian Chocolate Shake.',
    price: 349,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_combo_cheese_lava_box',
    petpoojaItemId: 'PP-CMB-203',
    name: 'Cheese Lava Monster Box',
    description: 'Cheese Lava Monster Burger + Cheesy Loaded Fries + Mint Mojito Sparkler.',
    price: 389,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_combo_duo_box',
    petpoojaItemId: 'PP-CMB-204',
    name: 'Burgonomics Duo Box (Serves 2)',
    description: '2 Burgers (Classic + Peri Peri), Large Cheesy Fries, 4pc Jalapeño Poppers, 2 Cokes.',
    price: 499,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_combo_family_mega_bundle',
    petpoojaItemId: 'PP-CMB-205',
    name: 'Family Mega Feast Bundle (Serves 4)',
    description: '4 Burgers of choice, 2 Large Peri Peri Fries, 8pc Onion Rings, 4 Gourmet Shakes.',
    price: 999,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1521305916504-4a1121188589?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_combo_aloo_tikki_budget_box',
    petpoojaItemId: 'PP-CMB-206',
    name: 'Aloo Tikki Value Saver Meal',
    description: 'Aloo Tikki Supreme Burger + Small Salted Fries + Thums Up Can.',
    price: 169,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_combo_smoky_bbq_meal',
    petpoojaItemId: 'PP-CMB-207',
    name: 'Smoky Portobello Combo',
    description: 'Smoky BBQ Portobello Burger + Herb Wedges + Hazelnut Cold Coffee.',
    price: 369,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_combo_mexican_fiesta',
    petpoojaItemId: 'PP-CMB-208',
    name: 'Mexican Fiesta Combo Box',
    description: 'Mexican Fiery Burger + Nachos with Queso + Fresh Lemonade.',
    price: 329,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1549611016-3a70d82b5040?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_combo_schezwan_crunch_pack',
    petpoojaItemId: 'PP-CMB-209',
    name: 'Szechuan Spice Combo',
    description: 'Schezwan Paneer Crunch Burger + Spicy Masala Fries + Berry Blast Mocktail.',
    price: 339,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_combo_kids_fun_box',
    petpoojaItemId: 'PP-CMB-210',
    name: 'Kids Happy Burger Box',
    description: 'Mild Sweet Corn Burger + Smiley Fries + KitKat Shake + Surprise Toy.',
    price: 249,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1583032015879-1c9ec8d011f0?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_combo_triple_threat_box',
    petpoojaItemId: 'PP-CMB-211',
    name: 'Triple Threat Heavy Combo',
    description: 'Double Decker Beast Burger + Loaded Paneer Fries + Chocolate Shake.',
    price: 429,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_combo_guac_healthy_box',
    petpoojaItemId: 'PP-CMB-212',
    name: 'Avocado Guac Clean Meal',
    description: 'Guacamole Smash Burger + Baked Wedges + Tender Coconut Cooler.',
    price: 379,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_combo_party_pack_10',
    petpoojaItemId: 'PP-CMB-213',
    name: 'Corporate Office Party Pack (10 Burgers)',
    description: '10 Assorted Gourmet Burgers + 5 XL Fries + 10 Beverages.',
    price: 2199,
    categoryId: 'cat_combos',
    image: 'https://images.unsplash.com/photo-1547584370-2cc98b8b8dc8?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },

  // --- Category 3: Crispy Sides & Fries (15 Items) ---
  {
    id: 'itm_side_french_fries_classic',
    petpoojaItemId: 'PP-SID-301',
    name: 'Classic Salted French Fries',
    description: 'Golden crispy potato fries seasoned with sea salt.',
    price: 89,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_peri_peri_fries',
    petpoojaItemId: 'PP-SID-302',
    name: 'African Peri Peri Masala Fries',
    description: 'Fries tossed in spicy African peri peri seasoning shaker bag.',
    price: 109,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_cheesy_loaded_fries',
    petpoojaItemId: 'PP-SID-303',
    name: 'Cheesy Jalapeño Loaded Fries',
    description: 'Crispy fries smothered in warm liquid cheddar cheese and chopped jalapeños.',
    price: 149,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_paneer_popcorn',
    petpoojaItemId: 'PP-SID-304',
    name: 'Crunchy Paneer Popcorn Bites',
    description: 'Bite-sized crispy spiced cottage cheese nuggets with garlic mayo dip.',
    price: 159,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_onion_rings',
    petpoojaItemId: 'PP-SID-305',
    name: 'Beer-Battered Crispy Onion Rings',
    description: 'Thick cut sweet Spanish onions in golden crispy batter with chipotle dip.',
    price: 119,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1639024471287-032f66e51c89?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_jalapeno_cheese_poppers',
    petpoojaItemId: 'PP-SID-306',
    name: 'Jalapeño Cheese Poppers (6 pcs)',
    description: 'Crumbed jalapeño shells stuffed with rich melted cream cheese.',
    price: 149,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1549611016-3a70d82b5040?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_garlic_breadsticks',
    petpoojaItemId: 'PP-SID-307',
    name: 'Cheesy Garlic Herb Breadsticks',
    description: 'Fresh baked breadsticks brushed with herb garlic butter and melted mozzarella.',
    price: 139,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_herb_potato_wedges',
    petpoojaItemId: 'PP-SID-308',
    name: 'Rosemary Garlic Potato Wedges',
    description: 'Chunky roasted potato wedges seasoned with fresh rosemary, sea salt, and garlic.',
    price: 119,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_nachos_grande',
    petpoojaItemId: 'PP-SID-309',
    name: 'Nachos Grande with Queso Dip',
    description: 'Stone ground corn tortilla chips served with warm queso dip and fresh salsa.',
    price: 149,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_truffle_parmesan_fries',
    petpoojaItemId: 'PP-SID-310',
    name: 'White Truffle & Veg Parmesan Fries',
    description: 'Hand cut fries drizzled with white truffle oil and vegetarian hard cheese shavings.',
    price: 179,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_crispy_corn_pepper',
    petpoojaItemId: 'PP-SID-311',
    name: 'Crispy Salt & Pepper Sweet Corn',
    description: 'Wok tossed crunchy corn kernels with crushed black pepper and scallions.',
    price: 129,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_mozzarella_sticks',
    petpoojaItemId: 'PP-SID-312',
    name: 'Crispy Mozzarella Sticks (5 pcs)',
    description: 'Golden fried breaded mozzarella with Italian marinara herb dipping sauce.',
    price: 169,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_sweet_potato_fries',
    petpoojaItemId: 'PP-SID-313',
    name: 'Crispy Sweet Potato Fries',
    description: 'Naturally sweet and crispy fries with honey mustard vegan dip.',
    price: 139,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_cheesy_dip_duo',
    petpoojaItemId: 'PP-SID-314',
    name: 'Burgonomics House Dip Duo',
    description: 'Trio of signature dips: Smoked Chipotle Mayo, Peri Peri Ranch, and Melted Cheddar.',
    price: 49,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_side_coleslaw_crunch',
    petpoojaItemId: 'PP-SID-315',
    name: 'Creamy Apple & Cabbage Slaw',
    description: 'Crisp red and green cabbage, grated granny smith apples, creamy dressing.',
    price: 79,
    categoryId: 'cat_sides',
    image: 'https://images.unsplash.com/photo-1521305916504-4a1121188589?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },

  // --- Category 4: Shakes & Beverages (15 Items) ---
  {
    id: 'itm_bev_dark_chocolate_shake',
    petpoojaItemId: 'PP-BEV-401',
    name: 'Belgian Dark Chocolate Thick Shake',
    description: 'Made with real Belgian chocolate, vanilla ice cream, and chocolate fudge sauce.',
    price: 159,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_kitkat_crunch_shake',
    petpoojaItemId: 'PP-BEV-402',
    name: 'KitKat Crunchy Caramel Shake',
    description: 'Crushed KitKat wafer bars, rich salted caramel swirl, whipped cream topping.',
    price: 169,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_alphonso_mango_shake',
    petpoojaItemId: 'PP-BEV-403',
    name: 'Alphonso Mango Thick Shake',
    description: 'Rich Ratnagiri Alphonso mango pulp blended with whole cream milk.',
    price: 149,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_hazelnut_cold_coffee',
    petpoojaItemId: 'PP-BEV-404',
    name: 'Hazelnut Iced Cold Coffee',
    description: 'Double espresso shot blended with chilled milk and roasted hazelnut syrup.',
    price: 139,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_mint_mojito',
    petpoojaItemId: 'PP-BEV-405',
    name: 'Fresh Mint Lime Mojito Sparkler',
    description: 'Muddled fresh garden mint, Persian lime juice, raw cane sugar, and sparkling club soda.',
    price: 119,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_berry_blast_cooler',
    petpoojaItemId: 'PP-BEV-406',
    name: 'Wild Berry Blast Iced Cooler',
    description: 'Crushed blueberries, strawberries, cranberry juice, lemon spritz.',
    price: 129,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_oreo_cookies_cream',
    petpoojaItemId: 'PP-BEV-407',
    name: 'Oreo Cookies & Cream Monster Shake',
    description: 'Crunchy Oreo cookie crumble blended with rich vanilla cream.',
    price: 159,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_lotus_biscoff_shake',
    petpoojaItemId: 'PP-BEV-408',
    name: 'Lotus Biscoff Speculoos Shake',
    description: 'Original Lotus Biscoff spread, speculoos cookie dust, caramel cream.',
    price: 179,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_strawberry_cheesecake',
    petpoojaItemId: 'PP-BEV-409',
    name: 'Strawberry Cheesecake Shake',
    description: 'Real strawberry puree, cream cheese swirl, and graham cracker dust.',
    price: 169,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_masala_lemonade',
    petpoojaItemId: 'PP-BEV-410',
    name: 'Desi Masala Lemonade (Shikanji)',
    description: 'Freshly squeezed lemon, roasted cumin, black salt, mint, and chilled soda.',
    price: 89,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_coke_can',
    petpoojaItemId: 'PP-BEV-411',
    name: 'Coca-Cola Can (300ml)',
    description: 'Chilled refreshing Coca-Cola can.',
    price: 40,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_thums_up_can',
    petpoojaItemId: 'PP-BEV-412',
    name: 'Thums Up Can (300ml)',
    description: 'Strong, fizzy Thums Up can.',
    price: 40,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_sprite_can',
    petpoojaItemId: 'PP-BEV-413',
    name: 'Sprite Can (300ml)',
    description: 'Clear lime fizzy Sprite can.',
    price: 40,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_iced_peach_tea',
    petpoojaItemId: 'PP-BEV-414',
    name: 'Iced Peach & Passionfruit Tea',
    description: 'Slow brewed Ceylon black tea infused with sweet peach nectar and lemon slice.',
    price: 109,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
  {
    id: 'itm_bev_mineral_water',
    petpoojaItemId: 'PP-BEV-415',
    name: 'Packaged Mineral Water (500ml)',
    description: 'Purified bottled drinking water.',
    price: 20,
    categoryId: 'cat_beverages',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=60',
    available: true,
    veg: true,
  },
];

/**
 * Synchronize a branch's menu with Petpooja catalog in Firestore.
 */
export async function syncPetpoojaMenuForBranch(branchId: string): Promise<{
  categoriesSynced: number;
  itemsSynced: number;
  syncedAt: Date;
}> {
  const batch = writeBatch(db);
  const now = Timestamp.now();

  // 1. Upsert Categories
  for (const cat of BURGONOMICS_DEFAULT_CATEGORIES) {
    const catRef = doc(db, 'menu', branchId, 'categories', cat.id);
    batch.set(
      catRef,
      {
        name: cat.name,
        sortOrder: cat.sortOrder,
        active: cat.active,
      },
      { merge: true }
    );
  }

  // 2. Upsert 63 Catalog Items
  for (const item of BURGONOMICS_63_ITEMS) {
    const itemRef = doc(db, 'menu', branchId, 'items', item.id);
    batch.set(
      itemRef,
      {
        ...item,
        lastSyncedAt: now,
      },
      { merge: true }
    );
  }

  // 3. Commit batch write
  await batch.commit();

  return {
    categoriesSynced: BURGONOMICS_DEFAULT_CATEGORIES.length,
    itemsSynced: BURGONOMICS_63_ITEMS.length,
    syncedAt: now.toDate(),
  };
}

/**
 * Check if the branch menu requires an hourly sync.
 */
export async function checkAndAutoSyncMenu(branchId: string): Promise<boolean> {
  try {
    const itemsSnap = await getDocs(collection(db, 'menu', branchId, 'items'));

    if (itemsSnap.empty) {
      await syncPetpoojaMenuForBranch(branchId);
      return true;
    }

    const firstDoc = itemsSnap.docs[0].data();
    const lastSynced: Timestamp | undefined = firstDoc.lastSyncedAt;

    if (!lastSynced) {
      await syncPetpoojaMenuForBranch(branchId);
      return true;
    }

    const ageInHours = (Date.now() - lastSynced.toMillis()) / (1000 * 60 * 60);
    if (ageInHours >= 1) {
      await syncPetpoojaMenuForBranch(branchId);
      return true;
    }

    return false;
  } catch (err) {
    console.warn('Error during auto-sync check:', err);
    return false;
  }
}
